# Generated by Django 2.2.6 on 2019-11-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(max_length=255)),
                ('prop_price', models.BigIntegerField()),
                ('prop_area', models.CharField(max_length=255)),
                ('prop_beds', models.IntegerField()),
                ('prop_bath', models.IntegerField()),
                ('prop_garage', models.IntegerField()),
                ('prop_image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
