# Generated by Django 2.2.6 on 2019-11-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_tagline', models.CharField(max_length=255)),
                ('agent_desc', models.TextField()),
                ('agent_phone', models.BigIntegerField()),
                ('agent_mobile', models.BigIntegerField()),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_skype', models.CharField(max_length=255)),
                ('agent_image', models.ImageField(default=None, upload_to='pics')),
            ],
        ),
    ]
